# -*- coding: utf-8 -*-
"""TensorsIntro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YlaxXsDCPJMFh28AVBJ9c_VqSUQwTG3l

A basic PyTorch tutorial from this [source](https://www.youtube.com/watch?v=BzcBsTou0C0&list=PLQVvvaa0QuDdeMyHEYc0gxFpYwHY2Qfdh).

- Tensor: multi-dimentional array
- Nice thing about torch is that we can put both the tensors on the GPU and do the math on the GPU (for now it is on the CPU)
"""

import torch
 x = torch.Tensor([5,3])
 y = torch.Tensor([2,1])

 print(x*y)

x=torch.zeros([2,5])
x1=torch.zeros(2)
print(x,x1)
x.shape

y = torch.rand([2,5])
y

"""## Reshaping

With numpy it is *.reshape* but with torch it is *.view*
"""

#Flattening operation
y.view([1,10])

#If you don't reassign it the shape would not change.
y

y=y.view([1,10])
y