# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdVh_u0g-lkI4-qqKOzcdXwvmiF5JdaK

### PyTorch tutorial #2

## TORCHVISION OBJECT DETECTION FINETUNING
For this tutorial, we will be finetuning a pre-trained [Mask R-CNN](https://arxiv.org/abs/1703.06870) model in the [Penn-Fudan Database](https://www.cis.upenn.edu/~jshi/ped_html/) for Pedestrian Detection and Segmentation. 

It contains 170 images with 345 labeled pedestrians, and we will use it to illustrate how to use the new features in torchvision in order to train an instance segmentation model on a custom dataset.
"""

